### ISSUE TITLE
Platform error climate.nobo_hub

### ISSUE THREAD

**Issue by VanGog86** [echoromeo/hanobo#10]
Good day. I have a problem. I have HA 0.100.3 installed. after installing hanobo I get the following error. how can I fix it. Thank you very much in advance

_Platform error climate.nobo_hub - cannot import name 'SUPPORT_OPERATION_MODE' from 'homeassistant.components.climate.const' (/home/pi/homeassistant/lib/python3.7/site-packages/homeassistant/components/climate/const.py)_

**Comment by VanGog86** [comment]
Good afternoon. tell me if there is news on my issue?

**Comment by echoromeo** [comment]
Hi, do you still have the problem? I updated to 0.103 a couple of days ago and did not see your problem

**Comment by echoromeo** [comment]
No response = the problem magically fixed? Closing
