### ISSUE TITLE
Platform error 0.104.3

### ISSUE THREAD

**Issue by eriksson25** [echoromeo/hanobo#12]
Hi, I have a fresh install of HA 0.104.3

But when I try to start hanobo I get following
[homeassistant.config] Platform error: climate - Integration 'nobo_hub host:150' not found.

My config file

```
# Nobø Energy Control
climate:
- platform: nobo_hub
    host:150
#    ip_address: [your nobø ip] # Uncomment if you do not want discovery
```

Any thing changed that broke it?

Edit. When changing to

```
# Nobø Energy Control
climate:
- platform: nobo_hub
    host: 150
#    ip_address: [your nobø ip] # Uncomment if you do not want discovery

```

It dont get same problem. Now I get

` ERROR (SyncWorker_0) [homeassistant.util.yaml.loader] mapping values are not allowed here
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 21, column 9
2020-02-05 20:51:39 ERROR (MainThread) [homeassistant.bootstrap] Error loading /home/homeassistant/.homeassistant/configuration.yaml: mapping values are not allowed here
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 21, column 9
`

**Comment by echoromeo** [comment]
Hi, this looks like whitespace issues of some kind? A copy/paste of my config is the following:
```
climate: 
 - platform: nobo_hub 
   host: !secret nobo_serial
```
Did the configuration validation pass?

Sorry for the late reply.

**Comment by echoromeo** [comment]
No response, closing
