### ISSUE TITLE
Remove temp settings for thermostats with only local control

### ISSUE THREAD

**Issue by aeklo** [echoromeo/hanobo#16]
Hi, great work!

Would it be possible to remove the temp settings for thermostats that only has local settings? I have some R80 RDC700, and it does not make sense for the settings to be visible.

Also, how about being able to select your own current temp sensor for thermostats not supporting this (only Switch does?).

**Comment by echoromeo** [comment]
Hi @aeklo, thanks!

1. I guess it should be possible. Will look into it. Personally I just set the temp settings in HA to the same as the local and leave them like that.
2. Linking in external temperature sensors is a great suggestion! However, I have no idea how to implement this, so if someone knows it would be great to get some help.

**Comment by oyvindwe** [comment]
I experimented a bit with this today. So far I have found four different variants of thermostats:
1. Set eco and comfort temperature on device only
   * RDC-700: serial prefix 160
   * TRB36 700: serial prefix 200
2. Set comfort temperature on device only, set eco temperature in hub only
   * R80 RSC 700: serial prefix 182
   * NCU-1R: serial prefix 184
   * DCU 1R: _serial prefix unknown_
3. Set eco and comfort temperature in hub only
   * TXF: Serial prefix 192
   * NCU-ER: serial prefix 198
   * DCU ER: _serial prefix unknown_
4. Set eco and comfort temperature on device or hub (will sync both ways)
   * NCU-2R: serial prefix 168
   * NTB-2R: serial prefix 210
   * DCU 2R: _serial prefix unknown_

Other known devices that don't support setting temperature:
   * RS-700 (serial prefix 120): switch (outlet)
   * Nobø Switch (serial prefix 234): control panel (reports temperature)

From the perspective of Home Assistant, 3 and 4 is the same (the temperature will also be reported to Home Assistent if changed on device).

As a zone may consist of device of different types, we need to check all the serial prefixes for all the devices in the zone.

If all devices only support setting temperature on device, we can remove support flag `SUPPORT_TARGET_TEMPERATURE_RANGE`:

![image](https://user-images.githubusercontent.com/5984518/119198980-900daa80-ba8a-11eb-856d-bb6e944c1ed2.png)

(this will hide the temperature value, but for some reason it is still possible to drag the green knob)

If all devices only supports setting eco temperature in hub, we can set support flag `SUPPORT_TARGET_TEMPERATURE`:

![image](https://user-images.githubusercontent.com/5984518/119199048-addb0f80-ba8a-11eb-938a-7bc8638057de.png)

(this is a bit misleading, as we're setting the low temperature)

If all devices support setting both eco and comfort temperatur in the hub, *or* we have an unknown device type, we can set support flag `SUPPORT_TARGET_TEMPERATURE_RANGE` as currently done:

![image](https://user-images.githubusercontent.com/5984518/119199161-e11d9e80-ba8a-11eb-8882-d8627407f209.png)


Note that technically it is always possible to set eco and comfort temperature for the _zone_ in Nobø Ecohub, so I'm tempted to not move forward with the implementation. What is currently shown as temperature range in Home Assistant reflects what's set in the hub.

**Comment by oyvindwe** [comment]
On 2, this has been proposed and rejected in Home Assistant: https://github.com/home-assistant/frontend/pull/8043

**Comment by echoromeo** [comment]
Archiving repo, closing issue
