### ISSUE TITLE
Not working in hass 0.89

### ISSUE THREAD

**Issue by bubbzy** [echoromeo/hanobo#2]
![54200887_419211435496333_5321779038853791744_n](https://user-images.githubusercontent.com/36682231/54394980-ba939a00-46ae-11e9-8819-f20fb1190113.png)

**Comment by NoKeRse** [comment]
I managed to get it up and running again with the following codechange on nobo_hub.py; 

from homeassistant.components.climate import (PLATFORM_SCHEMA,
    ClimateDevice, SUPPORT_OPERATION_MODE, 
    ATTR_TARGET_TEMP_LOW, ATTR_TARGET_TEMP_HIGH,
    SUPPORT_TARGET_TEMPERATURE_LOW, SUPPORT_TARGET_TEMPERATURE_HIGH)
from homeassistant.const import CONF_IP_ADDRESS, CONF_HOST, TEMP_CELSIUS, PRECISION_WHOLE
from homeassistant.components.climate.const import STATE_ECO
import homeassistant.helpers.config_validation as cv
from .pynobo.nobo import nobo

**Comment by echoromeo** [comment]
Thanks @NoKeRse! Fixed in the latest commit. 

BTW. folder name change is needed, see changes in readme
