### ISSUE TITLE
Seems to be some configuration issues regarding command_on

### ISSUE THREAD

**Issue by stigvi** [echoromeo/hanobo#20]
https://www.hjemmeautomasjon.no/forums/topic/4384-pynobo-nob%C3%B8-hub-python-interface/?do=findComment&comment=81571

**Comment by eirikwah** [comment]
I can confirm that it is easy to reproduce this bug. Do not include command_on or command_off configuration, and then this is shown in the log:

`2020-12-28 13:23:24 ERROR (MainThread) [homeassistant.components.homeassistant] Invalid config for [climate.nobo_hub]: expected a dictionary for dictionary value @ data['command_on']. Got None. (See ?, line ?). `

This actually fails the entire initialization of hanobo! :-(

**Comment by eirikwah** [comment]
Sorry for the bug I introduced. Pull request #21 fixes this. And this time I have tested more configuration combos... :-)
