### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by uphillbattle** [echoromeo/hanobo#26]
Is it just me, or is the integration not yet available i HACS?

Installation via HACS fails (for me) in step 4: When searching for Nobø (or hanobo, pynobo, nobo or any other variation) nothing comes up.

**Comment by rahnarsson** [comment]
I think it's due the some missing configurations on the other repositories based on the Validate-GitHub actions. If @echoromeo or @olekenneth needs help with this I'm happy to help! 

Thanks for the awesome integration so far!

**Comment by echoromeo** [comment]
@uphillbattle and @rahnarsson, yes please help :)
I have not managed the time to look at what the other repos require, it mostly looks like "paperwork"? :)

**Comment by uphillbattle** [comment]
Can it be as simple as replacing "ubuntu-latest" with "ubuntu-18.04" (or "ubuntu-20.04") in validate.yaml?

See https://github.com/actions/virtual-environments/issues/1816

**Comment by olekenneth** [comment]
No, it's just not added to hacs/default. You can do it manually until the requirements are met.

**Comment by uphillbattle** [comment]
@olekenneth Ah, yes, that worked. Thanks.

**Comment by rahnarsson** [comment]
Yeah, it requires "paperwork" but Topics should be enabled on this repo. I think I can handle the rest on the other repos.

**Comment by FrankBurmo** [comment]
Any update here on getting it included in hacs/default? As I understand it, somebody needs to make a PR for https://github.com/hacs/default ?

**Comment by FrankBurmo** [comment]
I added a quick PR for hacs/default (https://github.com/hacs/default/pull/869), but it seems an owner of the integrations-repo has to create the pr, so no luck for me :)

Also some pr-checks failed I see.

**Comment by echoromeo** [comment]
I created (hacs/default#870), so at least the owner check should work :)

**Comment by echoromeo** [comment]
But I realized now that was probably the wrong place to start. can you help adding it here? https://github.com/home-assistant/brands

**Comment by FrankBurmo** [comment]
Yes, I can look into it

**Comment by FrankBurmo** [comment]
The brands pr is ready, all checks passed.  just waiting for review: https://github.com/home-assistant/brands/pull/2348

**Comment by FrankBurmo** [comment]
brands pr is now merged.

**Comment by echoromeo** [comment]
Wheels pr ready, all checks passed. https://github.com/home-assistant/wheels-custom-integrations/pull/341

**Comment by olekenneth** [comment]
awesome work guys!

**Comment by echoromeo** [comment]
Looks like only review of hacs/default#870 is left now :)

**Comment by FrankBurmo** [comment]
Great!

**Comment by echoromeo** [comment]
Wohoo, we are in HACS :) ..now I just have to find the time to add HACS to my own home :)

**Comment by echoromeo** [comment]
And thank you for contributing guys! I believed it was too much work to add it, so I did not attempt doing it alone..

**Comment by FrankBurmo** [comment]
First time for me as well dealing with HACS, great to get some experience!

My motivation for coming here was being to handle integrations in my ha-installation (raspberry pi with zigbee) more controlled, rather than manually installing/configuring "this and that" :) 

Now I will start playing with this integration and see how it works for my Nobø-heated home. Happy to contribute!

**Comment by kaarnale** [comment]
Thank you all for this! Awesome work!
