### ISSUE TITLE
HA 2021.5.5 issue

### ISSUE THREAD

**Issue by stigvi** [echoromeo/hanobo#31]
After I upgraded to version 2021.5.5, I am not able to get the Nobø integration working

`2021-05-20 08:41:41 ERROR (MainThread) [homeassistant.components.climate] Error while setting up nobo_hub platform for climate

Traceback (most recent call last):
  
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  
File "/config/custom_components/nobo_hub/climate.py", line 81, in setup_platform
    hub = nobo(serial=host)
  
File "/usr/local/lib/python3.8/site-packages/pynobo.py", line 206, in __init__
    self._loop = asyncio.get_event_loop() if loop is None else loop
  
File "/usr/local/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'SyncWorker_6'.`

**Comment by stigvi** [comment]
OK, I see this is not related to HA 2021.5.5, but a new version of the pynobo library. I changed my own manifest file from "requirements": ["pynobo>=1.1.2"], to "requirements": ["pynobo==1.1.2"], and the Nobø integration does start now on my system.

**Comment by uphillbattle** [comment]
> OK, I see this is not related to HA 2021.5.5, but a new version of the pynobo library. I changed my own manifest file from "requirements": ["pynobo>=1.1.2"], to "requirements": ["pynobo==1.1.2"], and the Nobø integration does start now on my system.

This workaround works for me as well. Thanks.

**Comment by Gadget111** [comment]
I opened an issue at about the same time (I've closed it)
Thanks for putting up your work around!

**Comment by echoromeo** [comment]
@oyvindwe can you have a look at this?

**Comment by oyvindwe** [comment]
I'll investigate. pynobo 1.2.0 was supposed to be backwards compatible. Easiest fix is @stigvi 's workaround.

Note that I also just submitted a PR for official integration: https://github.com/home-assistant/core/pull/50913

**Comment by oyvindwe** [comment]
I think I see the problem. pynobo 1.2.0 will not work with hanobo 1.1.2, probably because an event loop already is in play.

**Comment by oyvindwe** [comment]
Apologies for this problem. I only tested the backwards compatibility using a standalone script, not with HA and hanobo 1.1.2

**Comment by uphillbattle** [comment]
Apologies are absolutely not required. Just glad that @stigvi and @oyvindwe found the solution. 😃

**Comment by oyvindwe** [comment]
@echoromeo I believe this issue can be closed now.
