### ISSUE TITLE
Dimplex Baseboard heater

### ISSUE THREAD

**Issue by helenclarko** [echoromeo/hanobo#34]
This might be a crazy request, but by any chance, would this work with the Dimplex Smart Baseboards?

I'm not sure if they have the same hub platform, but they are from the same company

**Comment by NoKeRse** [comment]
Do you have any information regarding the hub ? And possibly some links to some of the baseboards and the hub. GlenDimplex seem to differentiate quite a bit between different regions so direct links to the specific products can be of help,

One difference in regards of the hub, is that the NOBØ Energy Control hub aswell as the plugin modules ar
were developed in Norway. Sadly all of the R&D and production has been moved to Ireland. And I doubt that they have reused the codebase for the Energy Control. But I might be wrong . ;)

**Comment by helenclarko** [comment]
Yup, I think I might be out of luck here. I thought I might get lucky and find that the WIFI controller communicated over RF to the baseboard heaters and maybe I could relay the RF signal. If it is doing that, it's not doing if on frequencies I can monitor.

I'm a little lost for where to look next. 

It does look like someone did some work on a homebridge plugin, I'd really like to port that to home assistant, but I don't have a clue where to start with that.
https://github.com/NorthernMan54/homebridge-connex

Here is the heater anyway.

Connex Baseboard Heater:
https://www.dimplex.glendimplexamericas.com/en-us/electric-heaters/baseboard-heaters/connex-proportional-linear-convector#x-pc5020w31

WIFI controller:
https://www.dimplex.glendimplexamericas.com/en-us/electric-heaters/thermostats-and-controls/dimplex-wi-fi-multi-zone-programmable-controller#x-cx-wifi

**Comment by NoKeRse** [comment]
@helenclarko I'm not able to help here either. :( 
I tried to investigate a bit on the protocol they use. 
But most of the pages I found did not include any information regarding what kind of wireless protocol they use. 
How old are the solution you got ? But if you get a hold of what frequency they use, it imight be possible to check a bit further if they have been using any similar commands on your system. Cant imagine that they reinvent the wheel between systems and in different markets. Just my 5 cents on the case :) 

Have you tried sending them an email if there is any possibillity to get any documentation on the protocol they use for the communication between the Wifi Controller and the Baseboard heaters.

**Comment by DaveB93** [comment]
here's some information on the protocol. https://github.com/NorthernMan54/OpenNRF24L01/blob/master/Docs/connex.md

I don't have the system or the devices, a friend of a friend does, and is trying to not have to rip them out and get control via phone back.  I'm not sure what to do with the protocol,  do you know if this is potentially compatible with the nobo hub ?
