### ISSUE TITLE
Discovery doesn't work 

### ISSUE THREAD

**Issue by Odyno** [echoromeo/hanobo#39]
Hello,
I provided  a PR #38 with the increase of version of library with some fix about the asyncs methods. The reason is because I tried to use the original version and it didn't work either discovery or configuring it directly IP.

With the PR work the direct ip configuration but still not working the discovery. Probably there is also a small reformatting of the code due to the tool I use.

For the rest I was also working on the configuration via UI ( config_flow) but I preferred to divide the PR so as not to put too much meat on the fire

**Comment by echoromeo** [comment]
As mentioned in PR #38, the official integration takes over. I will archive this repo.
