### ISSUE TITLE
Update frequency of climate entity state and attribute

### ISSUE THREAD

**Issue by daandersson** [echoromeo/hanobo#4]
Hi @echoromeo and thank you for a great piece of software! When testing it I notice that, from the time I update the state or temp of the climate entity in HA, it takes ~30 sec (?) until the state is updated in the UI. Does the state only update on regular sync interval with the hub? Would it be possible to force an update right after temp or zone has been changed in HA?

**Comment by echoromeo** [comment]
Thanks! Glad you like it. Yes, it should be possible to force an update, but I am not sure how to do it the recommended way.

**Comment by echoromeo** [comment]
Fixed in [pynobo](https://github.com/echoromeo/pynobo/) on Jan 12, so should be solved for hanobo as well.
