### ISSUE TITLE
HeatPump DHW 250P / DHW 300 supported?

### ISSUE THREAD

**Issue by ChristophCaina** [echoromeo/hanobo#41]
Hi,
I would like to know, if this integration does support the Dimplex Heatpumps DHW250P or DHW300 ... and if yes, what requirements are given... 

currently, I am looking for a Heatpump for Warm-Water and found in some topics (IOBroker) that the DHW might support Modbus Protocol.
As far as I found out. there are some extensions available for dimplex heat pumps that enables the devices for Modbus RTU, Modbus TCP, App or other methods... therefore, I am looking if there's already an integration available - or if I need to continue my search / maybe need to create the Modbus Sensors & controlls on my own...

Thanks for your support, much appreciated :)

**Comment by echoromeo** [comment]
Hi Christoph,
Sorry, but this only support whatever is available through the Nobø Energy Control system: https://www.glendimplex.no/produkter/varmestyring/11123610/noboe-hub/c-77/p-330
I am quite sure heatpumps are not part of it.

Good luck with your search :)
