### ISSUE TITLE
Errors in log

### ISSUE THREAD

**Issue by bubbzy** [echoromeo/hanobo#5]
Hi!

Im getting a lot of errors in the log regarding updates of temperatures, Most of the time the it works though. Any idea why?

Running latest HA and the nobo hub I very close to the radiators.

Se attached file.
<img width="1152" alt="Skärmavbild 2019-05-06 kl  22 01 24" src="https://user-images.githubusercontent.com/36682231/57251961-602e0e80-704b-11e9-9867-a5ed1ea7e245.png">

**Comment by echoromeo** [comment]
hi, no idea. does it still do this?

**Comment by echoromeo** [comment]
No response = the problem magically disappeared? Closing
